version: "3.7"

services:
  diva:
    image: raise-opensim
    restart: unless-stopped
    build:
      context: opensim
      dockerfile: Dockerfile
    depends_on:
      - mariadb
      - lang
    networks:
      - raise_network
    ports: 
      - 9003:9003
      - 9003:9003/udp
    volumes:
    - ./backup:/diva-r09110/bin/backup
    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 1536M
        
  lang:
    image: raise-lang
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    networks:
      - raise_network
    ports:
      - 8030:80
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
  
  mariadb:
    image: mariadb:10.2.15
    restart: unless-stopped
    networks:
      - raise_network
    ports:
      - 3336:3306
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: divaopensim
    volumes:
      - opensim-vol:/var/lib/mysql
      - .:/etc/mysql/conf.d
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 384M
  restarter:
    image: docker
    volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
    command: ["/bin/sh", "-c", "while true; do sleep 600; docker restart testserver_lang_1; done"]
    restart: unless-stopped

networks:
  raise_network:
    external: false

volumes:
  opensim-vol:
     external:
       name: raise-vol